name: CD
on:
  push:
    tags:
      - "*.*.*"
permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: evm-json-rpc-cache-github-workflow
          aws-region: us-west-1
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - id: metadata
        run: |
          GITHUB_REF=${{ github.ref_name }}
          VERSION_REF="${GITHUB_REF//\//__}"
          echo "ref=${VERSION_REF}" >> "${GITHUB_OUTPUT}"
          echo "version=${VERSION_REF}-$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"
      - run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.metadata.outputs.ref }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.metadata.outputs.ref }}
